import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {City} from './city.js';
import {Rider} from './simulation.js';
import {LANDMARKS,unproject} from './spatial.js';
import {Crime,HOME,JOBS,snapJobs} from './missions.js';
import {Cop,lineOfSight,reinforce} from './police.js';

const $=id=>document.getElementById(id);
const canvas=$('world');let renderer,scene,camera,city,rider,horse,mixer,horseAction,sun,hemisphere,sky,horseGltf;
let ready=false,mode='start',previousTime=0,elapsed=0,orbit=0,pitch=.24,drag=null,cameraMode=0,soundOn=false,quality='high';
let hintUntil=0,toastUntil=0,discoveryUntil=0,lastUI=0,lastHoof=0,night=0,ambientAudio=null,lastReinforce=0;
const found=new Set(),keys=new Set(),cops=[],crime=new Crime();
const clockCamera=new THREE.Vector3(),cameraTarget=new THREE.Vector3();
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const palettes={golden:{skyTop:'#587e9e',skyBottom:'#d5c4ad',fog:'#b6bbc0',sun:'#ffdcab',intensity:3.1,hemi:2.05,exposure:1.0,pos:[-160,220,100],night:0},day:{skyTop:'#508ac2',skyBottom:'#c9e0e8',fog:'#c2d2dc',sun:'#fff1d7',intensity:3.35,hemi:2.4,exposure:1.02,pos:[-100,360,150],night:0},blue:{skyTop:'#1b3152',skyBottom:'#8799ad',fog:'#667b92',sun:'#a9c1ef',intensity:1.1,hemi:1.25,exposure:.94,pos:[-240,120,100],night:1}};
let lightMode='golden',goalMarker,homeMarker;

function fail(error){console.error(error);$('start-label').textContent='Unable to start';$('loading-detail').textContent=error.message?.includes('WebGL')?'This game needs WebGL2. Open it in a recent browser with hardware acceleration enabled.':'The world could not load. Reload the page to try again.';$('start-button').disabled=false;$('start-button').onclick=()=>location.reload()}
function setHint(text,seconds=4){$('hint').textContent=text;$('hint').classList.add('show');hintUntil=elapsed+seconds}
function toast(text,seconds=3.2){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=elapsed+seconds}
function clearInput(){keys.clear();drag=null}
function setMode(next){if(!ready&&next!=='start')return;mode=next;clearInput();document.body.classList.toggle('playing',next!=='start');for(const [id,active] of [['start-screen',next==='start'],['pause-screen',next==='pause'],['map-screen',next==='map'],['busted-screen',next==='busted'],['hud',next==='ride'],['ride-hud',next==='ride']])$(id).classList.toggle('hidden',!active);if(next==='map'){drawLargeMap();$('close-map').focus()}else if(next==='pause')$('resume-button').focus();else if(next==='busted')$('recover-button').focus();if(next!=='ride'&&ambientAudio)ambientAudio.gain.gain.setTargetAtTime(0,ambientAudio.ctx.currentTime,.2);else if(ambientAudio)ambientAudio.gain.gain.setTargetAtTime(soundOn?.035:0,ambientAudio.ctx.currentTime,.2)}
function start(){if(!ready)return;setMode('ride');cameraMode=0;orbit=0;toast('Welcome to Midtown. Follow the yellow marker.');canvas.focus()}
function travel(id){if(crime.stage!=='free'&&crime.current)throw new Error('Finish the job before fast travel');const place=LANDMARKS[id];if(!place)throw new Error('Unknown landmark');return dropAt(place.x,place.z,place.name)}
function dropAt(x,z,label){rider.place(x,z);orbit=0;pitch=.24;city.update(rider.x,rider.z,true);updateCamera(1,true);setMode('ride');if(label)setHint(label,3);return {place:label,position:unproject(rider.x,rider.z)}}
function recover(full=false){if(!full&&crime.stars>0){crime.money=Math.max(0,crime.money-100);toast('SURRENDERED · $100 fine')}crime.reset(full);rider.stamina=100;rider.exhausted=false;placeCops();dropAt(HOME.x,HOME.z,full?'Times Square':'Back at the stable')}

function setLight(value){const p=palettes[value];if(!p)return;lightMode=value;night=p.night;scene.fog.color.set(p.fog);sun.color.set(p.sun);sun.intensity=p.intensity;hemisphere.intensity=p.hemi;renderer.toneMappingExposure=p.exposure;sky.material.uniforms.topColor.value.set(p.skyTop);sky.material.uniforms.bottomColor.value.set(p.skyBottom);city?.setNight(p.night);$('time-select').value=value}
function setupScene(){
  renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xb6bbc0,.00063);camera=new THREE.PerspectiveCamera(57,innerWidth/innerHeight,.15,10000);
  hemisphere=new THREE.HemisphereLight(0xc4e1ff,0x746854,2.1);scene.add(hemisphere);sun=new THREE.DirectionalLight(0xffdcab,3.1);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.camera.near=1;sun.shadow.camera.far=700;sun.shadow.bias=-.0003;sun.shadow.normalBias=.3;sun.shadow.radius=3;scene.add(sun,sun.target);
  const skyMat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{topColor:{value:new THREE.Color()},bottomColor:{value:new THREE.Color()}},vertexShader:'varying vec3 vSky; void main(){vSky=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform vec3 topColor;uniform vec3 bottomColor;varying vec3 vSky;void main(){vec3 n=normalize(vSky);float h=pow(max(n.y,0.),.5);vec3 c=mix(bottomColor,topColor,h);float haze=pow(max(0.,dot(n,normalize(vec3(-.6,.2,.4)))),30.);c+=vec3(.22,.16,.09)*haze;gl_FragColor=vec4(c,1.);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')});
  sky=new THREE.Mesh(new THREE.SphereGeometry(7500,32,16),skyMat);sky.frustumCulled=false;sky.renderOrder=-100;scene.add(sky);setLight('golden');
  goalMarker=beacon('#ffe475',5);homeMarker=beacon('#74eadb',6);
}
function beacon(color,radius){const group=new THREE.Group();const ring=new THREE.Mesh(new THREE.RingGeometry(radius-.4,radius,40),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.85}));ring.rotation.x=-Math.PI/2;ring.position.y=.16;group.add(ring);const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,18,12,1,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}));shaft.position.y=9;group.add(shaft);const diamond=new THREE.Mesh(new THREE.OctahedronGeometry(1.1),new THREE.MeshBasicMaterial({color}));diamond.position.y=5;group.add(diamond);scene.add(group);return {group,diamond}}
function prepareHorseModel(model){model.scale.setScalar(.01);model.position.y=.045;model.traverse(mesh=>{if(!mesh.isMesh)return;mesh.castShadow=true;mesh.receiveShadow=true;const g=mesh.geometry;g.computeVertexNormals();if(g.morphAttributes.position&&!g.morphAttributes.normal){g.morphAttributes.normal=g.morphAttributes.position.map(morph=>{const temp=new THREE.BufferGeometry();temp.setIndex(g.index);const pos=g.attributes.position,values=new Float32Array(pos.array.length);for(let i=0;i<values.length;i++)values[i]=g.morphTargetsRelative?pos.array[i]+morph.array[i]:morph.array[i];temp.setAttribute('position',new THREE.BufferAttribute(values,3));temp.computeVertexNormals();const arr=new Float32Array(temp.attributes.normal.array);if(g.morphTargetsRelative)for(let i=0;i<arr.length;i++)arr[i]-=g.attributes.normal.array[i];temp.dispose();return new THREE.BufferAttribute(arr,3)})}})}
function makeHorse({lights=false,color=0xffffff}={}){
  const group=new THREE.Group();const model=horseGltf.scene.clone(true);prepareHorseModel(model);
  model.traverse(mesh=>{if(mesh.isMesh)mesh.material=new THREE.MeshStandardMaterial({color,vertexColors:true,roughness:.79,metalness:0})});
  group.add(model);scene.add(group);const mix=new THREE.AnimationMixer(model);const action=mix.clipAction(horseGltf.animations[0]);action.setDuration(1).play();action.paused=true;group.userData={mixer:mix,action};
  if(lights){const red=new THREE.Mesh(new THREE.SphereGeometry(.18,8,6),new THREE.MeshBasicMaterial({color:'#ff4747'}));red.position.set(-.42,2.35,.2);const blue=red.clone();blue.material=new THREE.MeshBasicMaterial({color:'#52c6ff'});blue.position.x=.42;group.add(red,blue);group.userData.lights={red,blue};red.visible=false;blue.visible=false}
  return group;
}
function blobShadow(){const shadowCanvas=document.createElement('canvas');shadowCanvas.width=128;shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d');const grad=ctx.createRadialGradient(64,64,4,64,64,64);grad.addColorStop(0,'rgba(0,0,0,.38)');grad.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grad;ctx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(3.8,5),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.115;scene.add(shadow);return shadow}
async function loadHorse(){horseGltf=await new GLTFLoader().loadAsync('./assets/horse.glb');prepareHorseModel(horseGltf.scene);horse=makeHorse();mixer=horse.userData.mixer;horseAction=horse.userData.action;horse.userData.shadow=blobShadow()}
function spawnCops(){
  const seeds=[LANDMARKS[1],LANDMARKS[2],LANDMARKS[4],LANDMARKS[5],LANDMARKS[6]];
  seeds.forEach((place,i)=>{const body=makeHorse({lights:true,color:0x3a4450});const cop=new Cop(city,body,i);try{cop.rider.place(place.x,place.z)}catch{cop.rider.place(HOME.x,HOME.z)}cops.push(cop)})
}
function placeCops(){cops.forEach((cop,i)=>{const place=[LANDMARKS[1],LANDMARKS[2],LANDMARKS[4],LANDMARKS[5],LANDMARKS[6]][i];try{cop.rider.place(place.x,place.z)}catch{cop.rider.place(HOME.x,HOME.z)}})}
function updateCamera(dt,snap=false){if(!rider)return;const reverse=cameraMode===2?Math.PI:0;const heading=rider.angle+orbit+reverse;const distance=cameraMode===1?5.3:cameraMode===2?10:10.8;const lookY=cameraMode===1?2.05:1.7;
  let targetDistance=distance;for(let d=2;d<=distance;d+=1){const x=rider.x-Math.sin(heading)*d,z=rider.z-Math.cos(heading)*d;if(city.blocked(x,z,.25,true)){targetDistance=Math.max(2.5,d-.8);break}}
  const speedLift=reducedMotion?0:Math.abs(rider.speed)*.027;
  clockCamera.set(rider.x-Math.sin(heading)*targetDistance,rider.y+2.0+Math.sin(pitch)*targetDistance+speedLift,rider.z-Math.cos(heading)*targetDistance);
  const follow=snap?1:1-Math.exp(-dt*6);camera.position.lerp(clockCamera,follow);
  cameraTarget.set(rider.x+Math.sin(rider.angle)*2,rider.y+lookY,rider.z+Math.cos(rider.angle)*2);camera.lookAt(cameraTarget);
  const fov=57+(reducedMotion?0:Math.max(0,Math.abs(rider.speed)-10)*.65);camera.fov+=(fov-camera.fov)*(snap?1:dt*3);camera.updateProjectionMatrix();sky.position.set(rider.x,0,rider.z);
}
function audioStart(){if(ambientAudio)return ambientAudio;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;const ctx=new Ctx(),gain=ctx.createGain();gain.gain.value=0;gain.connect(ctx.destination);const length=ctx.sampleRate*3,buffer=ctx.createBuffer(1,length,ctx.sampleRate),channel=buffer.getChannelData(0);let last=0;for(let i=0;i<length;i++){last=(last+(Math.random()*2-1)*.025)/1.025;channel[i]=last*3}const source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;const low=ctx.createBiquadFilter();low.type='lowpass';low.frequency.value=440;source.connect(low);low.connect(gain);source.start();ambientAudio={ctx,gain};return ambientAudio}
function toggleSound(){soundOn=!soundOn;const a=audioStart();if(a){a.ctx.resume();a.gain.gain.setTargetAtTime(soundOn&&mode==='ride'?.035:0,a.ctx.currentTime,.2)}$('sound-button').textContent=soundOn?'Sound on':'Sound off';$('sound-button').setAttribute('aria-label',soundOn?'Disable sound':'Enable sound')}
function playFx(type){if(!soundOn)return;const a=audioStart();if(!a)return;const t=a.ctx.currentTime,osc=a.ctx.createOscillator(),env=a.ctx.createGain();osc.type='triangle';osc.frequency.setValueAtTime(type==='jump'?250:type==='kick'?80:110,t);osc.frequency.exponentialRampToValueAtTime(35,t+.12);env.gain.setValueAtTime(.065,t);env.gain.exponentialRampToValueAtTime(.001,t+.12);osc.connect(env);env.connect(a.ctx.destination);osc.start();osc.stop(t+.13)}
function hoofbeat(){if(!soundOn)return;const a=audioStart();if(!a)return;const t=a.ctx.currentTime;for(let i=0;i<2;i++){const osc=a.ctx.createOscillator(),env=a.ctx.createGain();osc.type='triangle';osc.frequency.setValueAtTime(i?190:125,t+i*.042);osc.frequency.exponentialRampToValueAtTime(45,t+.075+i*.042);env.gain.setValueAtTime(.0001,t+i*.042);env.gain.exponentialRampToValueAtTime(.09,t+.003+i*.042);env.gain.exponentialRampToValueAtTime(.0001,t+.075+i*.042);osc.connect(env);env.connect(a.ctx.destination);osc.start(t+i*.042);osc.stop(t+.085+i*.042)}}
function interact(){if(mode!=='ride')return;const result=crime.interact(rider,city);if(!result)return;playFx('kick');if(result.toast)toast(result.toast);if(result.heat){lastReinforce=elapsed;reinforce(rider,cops,crime.stars)}}
function drawMap(canvas,large=false){if(!city||!rider)return;const ctx=canvas.getContext('2d');const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#142631';ctx.fillRect(0,0,w,h);let cx=rider.x,cz=rider.z,scale=.25;
  if(large){cx=(city.bounds[0]+city.bounds[2])/2;cz=(city.bounds[1]+city.bounds[3])/2;scale=Math.min((w-65)/(city.bounds[2]-city.bounds[0]),(h-65)/(city.bounds[3]-city.bounds[1]))}else scale=w/700;
  const to=p=>[(p[0]-cx)*scale+w/2,(p[1]-cz)*scale+h/2];
  function ring(r){ctx.beginPath();r.forEach((p,i)=>{const q=to(p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath()}
  ctx.fillStyle='#2c453d';for(const p of city.parks){ring(p.r);ctx.fill()}ctx.fillStyle='#223f51';for(const p of city.water){ring(p.r);ctx.fill()}
  ctx.lineCap='round';for(const r of city.roads){if(!r.drive)continue;ctx.strokeStyle=r.width>15?'#708085':'#435963';ctx.lineWidth=Math.max(large?.6:.75,r.width*scale*.43);ctx.beginPath();r.p.forEach((p,i)=>{const q=to(p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.stroke()}
  for(const p of LANDMARKS){const q=to([p.x,p.z]);if(q[0]<-10||q[0]>w+10||q[1]<-10||q[1]>h+10)continue;ctx.beginPath();ctx.arc(...q,large?7:3,0,Math.PI*2);ctx.fillStyle=found.has(p.id)?'#e7cc96':'#9aadb3';ctx.fill();if(large){ctx.fillStyle='#152631';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(p.id+1),...q)}}
  const home=to([HOME.x,HOME.z]);ctx.fillStyle='#74eadb';ctx.beginPath();ctx.arc(...home,large?8:4,0,Math.PI*2);ctx.fill();
  const goal=crime.target();if(goal){const q=to([goal.x,goal.z]);ctx.fillStyle='#ffe475';ctx.beginPath();ctx.arc(...q,large?8:5,0,Math.PI*2);ctx.fill()}
  if(crime.stars>0)for(const cop of cops){const q=to([cop.rider.x,cop.rider.z]);if(q[0]<-8||q[0]>w+8||q[1]<-8||q[1]>h+8)continue;ctx.fillStyle='#ed645e';ctx.beginPath();ctx.arc(...q,3,0,Math.PI*2);ctx.fill()}
  const pos=to([rider.x,rider.z]);ctx.save();ctx.translate(...pos);ctx.rotate(-rider.angle+Math.PI);ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(6,7);ctx.lineTo(0,4);ctx.lineTo(-6,7);ctx.closePath();ctx.fillStyle='#fff3cf';ctx.shadowBlur=8;ctx.shadowColor='#edce8b';ctx.fill();ctx.restore();ctx.fillStyle='#ccd5d7';ctx.font='11px Arial';ctx.textAlign='left';ctx.fillText('N ↑',14,22);
  if(large){ctx.fillStyle='#92a6ad';ctx.font='12px Arial';ctx.fillText('HUDSON RIVER',18,h-20);ctx.textAlign='right';ctx.fillText('EAST SIDE',w-18,h-20)}
}
function drawLargeMap(){if(!city)return;const c=$('large-map'),rect=c.getBoundingClientRect();c.width=Math.max(300,Math.floor(rect.width*1.5));c.height=Math.max(300,Math.floor(rect.height*1.5));drawMap(c,true)}
function updateMarkers(){const goal=crime.target();goalMarker.group.visible=!!goal&&mode!=='start';homeMarker.group.visible=mode!=='start';homeMarker.group.position.set(HOME.x,0,HOME.z);homeMarker.diamond.rotation.y=-elapsed;homeMarker.diamond.position.y=5+Math.sin(elapsed*2)*.4;if(goal){goalMarker.group.position.set(goal.x,0,goal.z);goalMarker.diamond.rotation.y=elapsed;goalMarker.diamond.position.y=5+Math.sin(elapsed*2)*.5}}
function updateHUD(){if(!rider)return;const speed=Math.abs(rider.speed);$('speed').textContent=String(Math.round(speed*3.6));$('speed-bar').style.width=`${speed/20*100}%`;$('gait').textContent=speed<.5?'AT EASE':speed<5?'WALK':speed<12?'CANTER':'GALLOP';const road=city.nearestRoad(rider.x,rider.z);$('street').textContent=road?.d<35&&road.road.name?road.road.name:'Off the avenue';let nearest=LANDMARKS[0];for(const p of LANDMARKS)if(Math.hypot(p.x-rider.x,p.z-rider.z)<Math.hypot(nearest.x-rider.x,nearest.z-rider.z))nearest=p;$('district').textContent=nearest.district;
  const bearing=((Math.atan2(Math.sin(rider.angle),-Math.cos(rider.angle))*180/Math.PI)+360)%360;$('heading').textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(bearing/45)%8];
  $('wanted').innerHTML='<b>★</b>'.repeat(crime.stars)+'<i>☆</i>'.repeat(5-crime.stars);$('wanted').setAttribute('aria-label',`Wanted level ${crime.stars} of 5`);$('money').textContent='$'+crime.money.toLocaleString();$('health').style.width=crime.health+'%';$('stamina').style.width=rider.stamina+'%';
  const job=crime.current;$('mission-label').textContent=job?`JOB 0${crime.job+1} / 0${JOBS.length} · $${job.reward.toLocaleString()}`:'MIDTOWN · FREE ROAM';$('mission-title').textContent=job?job.name:'THE CITY IS YOURS';
  $('objective').textContent=crime.stage==='pickup'?`Reach ${job.place}. Press E at the yellow marker.`:crime.stage==='evade'?'Break line of sight. Stay out of police view for 9 seconds.':crime.stage==='return'?'Bring the haul to the blue stable. Press E to deliver.':'All three jobs complete. Roam, jump, and cause a little trouble.';
  const goal=crime.target();$('distance').textContent=goal?`${Math.round(crime.distanceTo(rider,goal))} m to ${crime.stage==='return'?'stable':job.place}`:'';$('escape-wrap').classList.toggle('hidden',crime.stars===0);$('escape').style.width=`${crime.escape/9*100}%`;
  const prompt=crime.prompt(rider);$('prompt').classList.toggle('hidden',!prompt);$('prompt').innerHTML=prompt;
  for(const p of LANDMARKS)if(!found.has(p.id)&&Math.hypot(rider.x-p.x,rider.z-p.z)<95){found.add(p.id);$('discovery-name').textContent=p.name;$('discovery').classList.add('show');discoveryUntil=elapsed+5;$('found-count').textContent=`${found.size} / ${LANDMARKS.length} places`;document.querySelector(`[data-place="${p.id}"]`)?.classList.add('found')}
  $('found-count').textContent=job?`JOB ${crime.job+1} / ${JOBS.length}`:'FREE ROAM';
  drawMap($('minimap'));if(mode==='map')drawMap($('large-map'),true);
}
function frame(time){const dt=Math.min((time-previousTime)/1000||.016,.05);previousTime=time;elapsed+=dt;if(ready){
  if(mode==='ride'){
    rider.step(dt,{forward:keys.has('KeyW')||keys.has('ArrowUp'),back:keys.has('KeyS')||keys.has('ArrowDown'),left:keys.has('KeyA')||keys.has('ArrowLeft'),right:keys.has('KeyD')||keys.has('ArrowRight'),fast:keys.has('ShiftLeft')||keys.has('ShiftRight'),jump:keys.has('Space')});keys.delete('Space');
    const moving=Math.abs(rider.speed)>.25;horseAction.paused=!moving;horseAction.timeScale=Math.max(.3,Math.abs(rider.speed)/13);if(moving)mixer.update(dt);horse.position.set(rider.x,rider.y,rider.z);horse.rotation.y=rider.angle;const sh=horse.userData.shadow;sh.position.set(rider.x,.112,rider.z);sh.rotation.z=-rider.angle;sh.material.opacity=1-rider.y*.18;
    if(rider.bump&&Math.abs(rider.speed)>3&&elapsed>hintUntil+3)setHint('Turn to follow the street · R to reposition',3);
    if(moving&&rider.y<.1&&elapsed-lastHoof>Math.max(.2,.57-Math.abs(rider.speed)*.015)){hoofbeat();lastHoof=elapsed}
    if(!drag)orbit*=Math.exp(-dt*.6);
    const seen=new Set();for(const cop of cops){cop.update(dt,rider,crime.stars,elapsed);if(crime.stars>0&&lineOfSight(city,cop.rider.x,cop.rider.z,rider.x,rider.z))seen.add(cop)}
    if(crime.stars>0&&elapsed-lastReinforce>2.5){reinforce(rider,cops,crime.stars);lastReinforce=elapsed}
    for(const event of crime.update(dt,rider,cops,city,seen)){if(event.toast)toast(event.toast);if(event.busted){setMode('busted');toast('BUSTED.')}}
  }
  city.update(rider.x,rider.z);updateCamera(dt);updateMarkers();const p=palettes[lightMode].pos;sun.position.set(rider.x+p[0],p[1],rider.z+p[2]);sun.target.position.set(rider.x,0,rider.z);city.setNight(night);
  if(elapsed-lastUI>.17){updateHUD();lastUI=elapsed}
  if(elapsed>hintUntil)$('hint').classList.remove('show');if(elapsed>toastUntil)$('toast').classList.remove('show');if(elapsed>discoveryUntil)$('discovery').classList.remove('show');
  }renderer.render(scene,camera)
}
function bindControls(){
  $('start-button').onclick=start;$('resume-button').onclick=()=>setMode('ride');$('pause-button').onclick=()=>setMode('pause');$('restart-button').onclick=()=>recover(true);$('recover-button').onclick=()=>recover();$('map-button').onclick=()=>setMode('map');$('minimap-button').onclick=()=>setMode('map');$('close-map').onclick=()=>setMode('ride');$('sound-button').onclick=toggleSound;$('time-select').onchange=e=>setLight(e.target.value);$('quality-select').onchange=e=>{quality=e.target.value;renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='high'?1.7:1));city.visibleRadius=quality==='high'?920:650;city.update(rider.x,rider.z,true);sun.shadow.autoUpdate=true};
  for(const job of JOBS){const b=document.createElement('div');b.className='job-row';b.innerHTML=`<span>0${job.id+1}</span><strong>${job.name}</strong><em>${job.place} · $${job.reward.toLocaleString()}</em>`;$('job-list').append(b)}
  for(const p of LANDMARKS){const b=document.createElement('button');b.dataset.place=p.id;const num=document.createElement('span');num.textContent=String(p.id+1).padStart(2,'0');b.append(num,document.createTextNode(p.name));b.onclick=()=>{try{travel(p.id)}catch(error){toast(error.message)}};$('destinations').append(b)}
  window.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&mode==='ride'&&e.code!=='Tab')e.preventDefault();if(e.repeat&&['Escape','KeyM','KeyC','KeyR','KeyE','Space'].includes(e.code))return;if(e.code==='Escape'){if(mode==='ride')setMode('pause');else if(mode==='pause'||mode==='map')setMode('ride');return}if(e.code==='KeyM'&&ready&&mode!=='start'&&mode!=='busted'){setMode(mode==='map'?'ride':'map');return}if(mode!=='ride')return;if(e.code==='KeyE'){interact();return}if(e.code==='KeyC'){cameraMode=(cameraMode+1)%3;setHint(['Chase camera','Close camera','Front camera'][cameraMode],2)}else if(e.code==='KeyR'){if(crime.stars>0)recover();else{rider.place(rider.x,rider.z);updateCamera(1,true);setHint('Back on the street',2)}}else keys.add(e.code)});
  window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(mode==='ride')setMode('pause');clearInput()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='ride')setMode('pause')});
  canvas.addEventListener('pointerdown',e=>{if(mode!=='ride')return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;orbit-=(e.clientX-drag.x)*.004;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-drag.y)*.003,-.04,.8);drag.x=e.clientX;drag.y=e.clientY});const stopDrag=()=>drag=null;canvas.addEventListener('pointerup',stopDrag);canvas.addEventListener('pointercancel',stopDrag);canvas.addEventListener('wheel',e=>{if(mode==='ride'){e.preventDefault();pitch=THREE.MathUtils.clamp(pitch+e.deltaY*.0006,-.04,.8)}},{passive:false});
  for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(b.dataset.key==='KeyE')interact();else keys.add(b.dataset.key)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key))}
  window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(mode==='map')drawLargeMap()});
}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const controller=new AbortController();const list=[{name:'get_exploration_state',description:'Read horse location, wanted level, current job, and discovered landmarks.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return {mode,position:unproject(rider.x,rider.z),speedKmh:Math.round(Math.abs(rider.speed)*3.6),job:crime.current?.name||'free roam',stage:crime.stage,stars:crime.stars,money:crime.money,health:crime.health,discovered:[...found].map(i=>LANDMARKS[i].name)}}},{name:'ride_from_landmark',description:'Move the horse to an accessible street near a Manhattan landmark. Blocked during an active job.',inputSchema:{type:'object',properties:{landmarkId:{type:'integer',minimum:0,maximum:7}},required:['landmarkId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Number.isInteger(input.landmarkId)||input.landmarkId<0||input.landmarkId>7)throw new Error('landmarkId must be an integer from 0 through 7');return travel(input.landmarkId)}}];for(const tool of list)try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>controller.abort(),{once:true})}
async function init(){try{setupScene();bindControls();renderer.setAnimationLoop(frame);const [response]=await Promise.all([fetch('./assets/manhattan.json'),loadHorse()]);if(!response.ok)throw new Error('Map request failed');const data=await response.json();$('loading-detail').textContent='Placing buildings, avenues, and street details';await new Promise(resolve=>setTimeout(resolve,30));city=new City(scene,data);snapJobs(city);rider=new Rider(city);rider.place(HOME.x,HOME.z);city.update(rider.x,rider.z,true);spawnCops();horse.position.set(rider.x,0,rider.z);horse.rotation.y=rider.angle;horse.userData.shadow.position.set(rider.x,.112,rider.z);updateCamera(1,true);ready=true;$('start-label').textContent='Steal the oats';$('loading-detail').textContent='Midtown is open. Your ride starts at the Times Square stable.';$('start-button').disabled=false;updateHUD();registerTools()}catch(error){fail(error)}}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(ready)setMode('pause');setHint('Graphics paused. Reload the page to restore the world.',999)});
init();
